// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef CTaLibViewUI_h
#define CTaLibViewUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>

class CTaLibFuncViewUI {
public:
  Fl_Double_Window* CTaLibViewUI();
  Fl_Double_Window *m_window;
};
#endif
