// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "CTaLibViewUI.h"

Fl_Double_Window* CTaLibFuncViewUI::CTaLibViewUI() {
  { m_window = new Fl_Double_Window(100, 100);
    m_window->user_data((void*)(this));
    m_window->end();
  } // Fl_Double_Window* m_window
  return m_window;
}
